-- Drop tables if they exist (clean start)
DROP TABLE IF EXISTS DELIVERY_TRACKING;
DROP TABLE IF EXISTS ORDER_ITEMS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS DRIVER_PROFILES;
DROP TABLE IF EXISTS CUSTOMER_PROFILES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ANNOUNCEMENTS;
