@baseUrl = http://localhost:3000/api

# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "kuljettaja@quantix.fi",
    "password": "driver123"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "admin@quantix.fi",
    "password": "admin",
    "role": "admin"
}
