@baseUrl = http://localhost:3000/api/v1

# @name login

###
@token = {{login.response.body.token}}

### Testaa sijainnin päivitystä
POST {{baseUrl}}/deliveries/10124244/location
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "latitude": 63.2699,
    "longitude": 22.731,
    "status": "in_transit"
}





###
GET {{baseUrl}}/deliveries/1012221124/status
Authorization: Bearer {{token}}
