@baseUrl = http://localhost:3000/api
@token = {{login.response.body.token}}

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "asiakas1@quantix.fi",
    "password": "driver123"
}

###

# Tämä testi triggeröi nyt bäkkärillä geokoodauksen delivery_address-kentän perusteella.
POST {{baseUrl}}/orders
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "delivery_address": "TIKKURILANTIE 1",
    "notes": "Soita ovikelloa, summeri on rikki.",
    "scheduled_delivery": "2026-04-29 15:00:00",
    "items": [
        {
            "product_id": 1,
            "quantity": 2
        }
    ]
}

###

### Testaa virhetilanne: Puuttuvat tuotteet
POST {{baseUrl}}/orders
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "delivery_address": "Rukkilanpolku, Helsinki",
    "items": []
}

###

### Hae asiakkaan omat tilaukset
GET {{baseUrl}}/orders/my-orders
Authorization: Bearer {{token}}

# HAE KULJETTAJALLE MÄÄRÄTYT TOIMITUKSET
###
GET {{baseUrl}}/orders/assigned
Authorization: Bearer {{token}}
