@baseUrl = http://localhost:3000/api

# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "admin@quantix.fi",
    "password": "admin"
}

###
@token = {{login.response.body.token}}

### Testaa sijainnin päivitystä
POST http://localhost:3000/api/deliveries/101/location
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "latitude": 60.2699,
    "longitude": 24.2384,
    "status": "in_transit"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "admin@quantix.fi",
    "password": "admin",
    "role": "admin"
}


# HAE KULJETTAJALLE MÄÄRÄTYT TOIMITUKSET
###
GET http://localhost:3000/api/orders/assigned
Authorization: Bearer {{token}}

### 1. Hae asiakkaan kaikki omat tilaukset

GET {{baseUrl}}/orders/my-orders
Authorization: Bearer {{token}}

