
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "kuljettaja@quantix.fi",
    "password": "driver123"
}

###
@token = {{login.response.body.token}}

### Testaa sijainnin päivitystä
POST http://localhost:3000/api/deliveries/101/tracking
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "latitude": 60.2699,
    "longitude": 24.2384,
    "status": "in_transit"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "kuljettaja@quantix.fi",
    "password": "driver123",
    "role": "driver"
}


# HAE KULJETTAJALLE MÄÄRÄTYT TOIMI
###
GET http://localhost:3000/api/orders/assigned
Authorization: Bearer {{token}}

